name: skillet

views:

  - name: ''
    class: CNCView
    menu: Iron Skillet
    menu_option: Welcome
    attributes:
      template_name: pan_cnc/welcome.html
    context:
      title: Skillet
      description: Iron-Skillet Configurations
      documentation_link: http://iron-skillet_panorama_dg.readthedocs.io

  - name: ironskilletconfig
    class: ChooseSnippetByLabelView
    menu: Iron Skillet
    menu_option: Iron Skillet Configuration
    attributes:
      label_name: service_type
      label_value: iron_skillet
      header: Step 1
      title: Select Configuration Option
      next_url: workflow01

  - name: workflow01
    class: IronSkilletWorkflow01
    attributes:
      next_url: ironskilletprovision

  - name: ironskilletprovision
    class: IronSkilletProvisionView

  - name: provision
    class: ProvisionSnippetView





